# Generated by Django 3.1.4 on 2021-01-02 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schooltrackapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='completedcourse',
            old_name='user',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='currentundertakencourse',
            old_name='user',
            new_name='student',
        ),
    ]
