# Generated by Django 3.1.4 on 2021-01-02 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schooltrackapp', '0002_auto_20210102_0544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_credits',
            field=models.IntegerField(max_length=3),
        ),
    ]
