# Generated by Django 3.1.4 on 2021-01-02 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schooltrackapp', '0004_auto_20210102_0614'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentUndertakenCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_course_registration', models.DateField(auto_created=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schooltrackapp.course')),
            ],
        ),
    ]
