# Generated by Django 3.1.4 on 2021-01-04 00:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schooltrackapp', '0004_course_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedcourse',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='completed_course', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='currentundertakencourse',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
