# Generated by Django 3.1.4 on 2021-01-04 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schooltrackapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='completedcourse',
            old_name='student',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='student',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='currentundertakencourse',
            old_name='student',
            new_name='owner',
        ),
    ]
