# Generated by Django 3.1.4 on 2021-01-04 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schooltrackapp', '0002_auto_20210104_0127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='completedcourse',
            old_name='owner',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='owner',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='currentundertakencourse',
            old_name='owner',
            new_name='student',
        ),
    ]
